[profile.default]
src = "src"
out = "out"
libs = ["lib"]
fs_permissions = [
    { access = "read", path = "./img/" },
    { access = "read", path = "./broadcast" },
]
ffi = true
remappings = ['@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/']